server:
  port: 8626
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: tishengke
  profiles:
    active: dev
  config:
    import:
      - optional:application-private.yml
  #  更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
